version: '3.7'
services:
  mercure:
      restart: unless-stopped
      image: dunglas/mercure:v0.10.4
      environment:
        - PUBLISHER_JWT_KEY=blabla
        - SUBSCRIBER_JWT_KEY=blabla
        - CORS_ALLOWED_ORIGINS=*
        - PUBLISH_ALLOWED_ORIGINS=*
        - ALLOW_ANONYMOUS=1
        - MERCURE_EXTRA_DIRECTIVES=cors_allowed_origins *
      ports:
        - 8001:80