version: '3.7'
services:
  mercure:
    container_name: mercure_docker_symfony
    restart: unless-stopped
    image: dunglas/mercure:v0.10.4
    environment:
        - PUBLISHER_JWT_KEY=mercure_publisher
        - SUBSCRIBER_JWT_KEY=mercure_subscriber
        - CORS_ALLOWED_ORIGINS=*
        - PUBLISH_ALLOWED_ORIGINS=*
        - ALLOW_ANONYMOUS=1
        - MERCURE_EXTRA_DIRECTIVES=cors_allowed_origins *
        - SERVER_NAME=":80"
    ports:
        - 8001:80
